project:
  type: book

book:
  title: "Policy Learning and Information Processing Dynamics"
  author: ""
  date: ""
  chapters:
    - index.qmd
    - chap1.qmd
    - chap2.qmd
    - chap3.qmd
    - chap4.qmd
    - chap5.qmd
    - chap6.qmd 
    - references.qmd

bibliography: /Users/matthewnowlin/Library/CloudStorage/OneDrive-UTArlington/01-RESEARCH/Manuscript-Files/refs.bib
csl: /Users/matthewnowlin/Library/CloudStorage/OneDrive-UTArlington/01-RESEARCH/Manuscript-Files/csl/apa-7th.csl
link-bibliography: false
fig-cap-location: top
fontfamily: ebgaramond

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt
  docx:
    reference-doc: default.docx



