# Concluding Remarks: What This Element Does, and What Comes Next

## Revisiting Conceptual, Theoretical, and Analytical Approaches to Policy Learning

In the first chapter of this element, we started with the question of why, how, and when policy actors do what they do, a question the answer to which has long been a central quest for public policy scholarship. Among the different theoretical approaches that were developed to answer this question, policy learning stands out as one of the most omnipresent and potent. In reviewing the learning literature in the second chapter, we illustrated how, in an attempt to answer the aforementioned question, policy learning research has grown to become an active research field sprawling with various conceptual and theoretical approaches underpinned by different ontological-epistemological positions from mechanistic, positivist, interpretivist, to social constructivist [@zakiPolicyLearningGovernance2024; @zakiMeasuringPolicyLearning2024]. With such rich and diverse foundations, various theoretical descriptors of policy learning processes have emerged, resulting in a wide range of types, mechanisms, forms, modes, of learning leading to different outcomes. Those were developed through – and deployed in a wide range of analytical approaches scaling up and down between micro-foundations and individual learning dynamics, collectives, and systems [see @heikkilaBuildingConceptualApproach2013; @dunlopLearningBathTubMicro2017; @nowlinPolicyLearningInformation2021; @zakiHowDoesPolicy2023]. There, and as shown in @tbl-learn-concept, we see learning being analytically employed in various ways, each anchored in specific conceptual approaches, from mechanistic and process-oriented to paradigmatic, ideational, and outcome-oriented. 

This theoretical versatility of policy learning has led to it being viewed as an ontology of the policy process, which is being recognized as providing a coherent and robust explanatory view of why policy actors do what they do, as a function of how, why, and when they learn about policy problems [see @kamkhajiPolicyLearningEuro2022]. This is premised on an overarching understanding of the learning process as "policy-embedded," where policy actors seek and/or process information and knowledge about policy problems while being embedded within a particular policy context, and where the information and knowledge they collate interacts with different institutional structures therein [see @zakiSystematicReviewPolicy2022]. This policy-embedded learning process is accordingly viewed as the driver for different policy behaviors, regardless of normative assessments of the quality of learning outcomes. For example, being traceable to updates in policy-issue understandings, beliefs, and potentially, from there on, updates in policy-related behaviors, from advocacy to varying degrees of policy change. By adopting this micro-foundational perspective, policy learning is seen as the kernel and nucleus of individual and collective behavior. We then carried this fundamental approach to policy learning over to Chapter 3, pursuing the second contribution of this element, to which we now turn. 

## A Deeper Understanding of Policy Learning Dynamics: An Information Processing Approach

In Chapter 3, we pivoted from the background conceptualization of policy learning to examine the micro-foundations of how learning occurs. This is by tracing and analyzing the role of information – the building block or raw material of the learning process – and how it interacts with pre-existing belief structures. To do so, we constructed a model of policy learning and information processing. This model focuses on belief change as the main learning outcome, operationalizing four varieties as a function of the interaction between pre-existing beliefs and inbound information, including no learning, belief decay, belief reinforcement, and belief change. We then used many years’ worth of public opinion data from the US about nuclear energy in Chapter 4. We leveraged this data to explore the process of learning regarding updating beliefs and preferences following the information signal of the risks of nuclear energy provided by the 2011 accident at the nuclear power plant in Fukushima, Japan. That example showed belief change regarding the risks and benefits of nuclear energy as well as preference change regarding the construction of new nuclear power plants congruent with the information.   

After developing the policy learning and information processing model, in Chapter's 3 and 4, we placed the micro-foundational model within the broader context of policymaking, which includes information, information processing by policy actors and institutions, and policy learning. We also discussed pathways from policy learning to policy change, which includes belief change, preference change, behavior change, and policy change. For policy change to happen as a result of policy learning through information processing, all elements must be aligned and consistent with the information. This means that belief change must be consistent with the information, preference change must be consistent with belief change, behavior change must be consistent with belief and preference change, and policy must be consistent with belief, preference, and behavior change. 

## What Comes Next? Avenues for Future Research

Having discussed our model of policy-embedded learning and information processing, we now turn to avenues for future research. The first avenue concerns the analytical level scalability of this model. As earlier noted, learning occurs within and across various levels, micro, meso, and macro, spanning individuals, collectives (such as advocacy coalitions, policy subsystems, interest groups, and organizations) as well as systemically. Furthermore, learning not only occurs within these levels but also travels across them [@heikkilaBuildingConceptualApproach2013; @dunlopLearningBathTubMicro2017;@zakiSystematicReviewPolicy2022]. Banking on the interactions between clear structural dimensions of policy actors, information and knowledge, and structures (whether cognitive or institutional), the policy learning through information processing model is highly scalable across levels. As such, future research can apply this model across multiple levels of analysis, for example, within particular collectives such as networks, advocacy coalitions, or organizations where the underlying mechanisms of interaction between prior beliefs, information processing, and weighted posterior beliefs are assumed at each level. Furthermore, and in terms of analytical level-scalability, this approach could also be applied across levels as, for example, tracing how individual learning connects to coalition learning, which then connects to subsystem learning. 

The second avenue for future research concerns theoretically scaling up this model and embedding it within other theoretical perspectives of learning to enhance their explanatory potential. This could include various types, modes, mechanisms, and forms of learning. For example, this includes empirically tracing instrumental learning processes (mostly focused on policy instrument calibrations) through analyzing the processing of information related to secondary beliefs. Similarly, future research can pursue the same approach within other modes of learning, whether epistemic, hierarchical, reflexive, or bargaining-oriented. This also extends to learning mechanisms, whereby the interaction between information and cognitive structures can be traced within inferential learning, where information signals are carefully considered and weighted, versus the case of contingent learning, where crises or focusing events quickly shift how issues are defined and reshuffle policy priorities. 

Finally, research should explore how to connect the learning model to policy innovation. Policy innovation ... 


## Policy Change Beyond Learning  

While the focus of this Element has been policy learning, there are several other ways in which policy change may occur. It is important to note the limits of our approach as an explanation for policy change. ACF scholarship notes that apart from policy-oriented learning policy change, both major (change associated with policy core) and minor (change associated with secondary aspects) can result from events both external and internal to the policy subsystem [@nohrstedtAdvocacyCoalitionFramework2023]. Events or shocks can include changes in socioeconomic conditions, shifts in public opinion, changes in governing arrangements, elections, scandals, policy failures, or crises or disasters. Such events can constitute a strong information signal that leads to policy learning, such as in the cases of the Fukushima accident, the COVID-19 pandemic, or the Russian invasion of Ukraine, among others. However, apart from learning, events can lead to policy change through shifts in the resources available to coalitions or when a coalition pushing for policy change is able to exploit a policy window that opens as a result of the event [@nohrstedtLogicPolicyChange2010]. 

The ACF also notes that policy change can happen as a result of a negotiated agreement between coalitions [@sabatierAdvocacyCoalitionFramework2007]. Negotiated agreements involve deliberation, compromises, and trade-offs between adversarial coalitions, which result in policy changes. Such agreements are more likely in the presence of a "hurting stalemate" or a situation where the status quo is unacceptable to the coalitions, and there are no other policy venues in which to engage [@nohrstedtAdvocacyCoalitionFramework2023]. Finally, policy change can happen as a result of shifts in power between coalitions [@piercePolicyChangeAdvocacy2020]. Power shifts between coalitions can happen as a result of events such as an election that favors elected officials of one coalition, and newly available resources for a coalition such as a powerful elected official, or knowledgeable experts [@nowlinAdvocacyCoalitionsPolitical2022], among others.

While information processing is at the heart of our approach to learning in this element, policy change can also happen as a result of attention to information without any changes in beliefs or preferences [@workmanInformationProcessingPolicy2009]. Policy actors have multiple and perhaps competing policy preferences. Policy change can happen when one preference becomes more salient than another in the absence of learning or preference updating. One example from @jonesReconceivingDecisionMakingDemocratic1994 is the consideration of the US Congress in 1991 and again in 1992 to fund the construction of the superconducting super collider, a particle accelerator that would have been built in Texas. Seventy-nine US House of Representatives members voted in favor of funding the super collider in 1991 but subsequently voted against funding in 1992. The shift in votes by the Seventy-nine members of Congress was likely a result of the issue of the budget deficit gaining more attention and making the preference for a smaller deficit (and perhaps re-election) more salient.

In this Element, we started with a review and mapping of the different theoretical directions in the policy learning literature, illustrating the potential for integrating an information processing approach therein. In oue view, this Element has demonstrated the substantial promise of the information processing approach to enhancing the analytical utility of policy learning research. By tracing how information is processed and reconciled against cognitive and institutional structures, this approach offers a more nuanced understanding of the micro-foundations of policy learning. It also helps advance the analytical utility of different theoretical approaches to learning. By acknowledging the cognitive processes that underpin policy decisions, scholars can gain deeper insights into the dynamics of policy change and the factors that influence learning across different contexts.





<!-- In this element we provided a brief overview of literature on policy learning and developed a model and framework illustrating the dynamics of information processing and policy learning. We also explored the implications of our approach with several application, including learning among the US public regarding nuclear energy following the accident at Fukushima, COVID-19, and ... 


## Revisting the Key Conceptual, Analytical, and Theoretical Approaches to Policy Learning 

In Chapter 1 we laid out a brief overview of the conceptual, analytical, and theoretical approaches to policy learning in the literature. Here we connect our model and framework to those approaches. As shown in @tbl-learn-concept, conceptual approach to learning include mechanism and process-oriented, paradigmatic, outcome-oriented, and ideational. Mechanism and process-oriented approach to learning examines the underlying ways in which learning happens. In our framework, the mechanism and processes are described by the model of policy learning and information processing discussed in Chapter 2. A paradigmatic approach to learning sees policy learning as a broader approach, or style, of policymaking. The information processing and policy-embedded learning framework may be seen as paradigmatic because it center learning as a key element of policy change and encompasses information and information processing by policy actors and institutions as central to learning. Outcome-oriented approaches to learning focus on the products, or results of learning. The model of policy learning and information processing focuses on the outcome of belief change and predicts four possible outcomes, including no learning, belief decay, belief reinforcement, and belief change. In addition to belief, the framework suggests that preference change, behavior change, and policy change are possible outcomes of policy learning. Finally, an ideational approach to policy learning focuses on the transfer or diffusion of ideas and policies. Neither our model or out framework examine policy diffusion directly; however, ideas and policies from other times and places could certainty be among the various information signals that actors and institution receive and either process or ignore.     

As noted, learning occurs within and across various level, including the micro, meso, and macro level as well as multidimensional and non-linear learning (see @tbl-learn-levels). Our model, discussed in Chapter 2, can be applied at the micro level with individuals, at the meso level with coalitions within subsystems, and at the macro level with institutions, systems, structures, and networks. At each level the underlying mechanisms of prior beliefs, information processing and weighted, and posterior beliefs are assumed. Finally, our approach works across levels as, for example, individual learning connects to coalition learning which connects to subsystem learning, subsystem learning connects to macro learning. Additionally, our approach can account for learning across time and space.     

@tbl-learn-descript laid several theoretical perspectives of learning, including types of learning, modes of learning, mechanisms of learning, forms of learning, and degrees of learning. Our model and framework are intended to be generalizable and therefore able to account for the various types of learning, including instrumental, social, political, and organizational learning. With our approach the type of learning is a function of the beliefs and information. For example, instrumental learning would result from changes in secondary beliefs based on information about various policy instruments. Of note, our approach, with its' focus on beliefs and belief updating, draws heavily from policy-oriented learning. Additionally, our approach can account for various modes of learning, including epistemic, hierarchical, reflexive, and bargaining-oriented. In our framework, the mode of learning is a function of the systems and structures in which policy actors are embedded. In Chapter 1, we noted two mechanisms of learning: inferential and contingent. With our approach, inferential can occur as information signals are carefully considered and weighted, whereas, contingent learning occurs as a crisis or focusing event quickly shifts how an issue is defined, such as the case of US public opinion on nuclear energy following the Fukushima accident. Forms of learning include lesson drawing and policy transfer which can be captured by our approach. Finally, the degrees of learning from single to quadruple loop learning can be captured by our approach as learning through information processing works through each degree.   


## Policy Change Without Policy Learning 

While the focus of this Element has been policy learning, there are several other ways in which policy change may occur. It important to note the limits of our approach as an explanation for policy change. ACF scholarship notes that apart from policy-oriented learning policy change, both major (change associated with policy core) and minor (change associated with secondary aspects), can result from events both external and internal to the policy subsystem [@nohrstedtAdvocacyCoalitionFramework2023]. Events or shocks can include changes in socioeconomic conditions, shifts in public opinion, changes in governing arraignments, elections, scandals, policy failures, or a crisis or disaster. Such events can constitute a strong information signal that leads to policy learning such as the Fukushima accident or the COVID-19 pandemic discussed in this Element. However, apart from learning, events can lead to policy change through shifts in the resources available to coalitions or when a coalition pushing for policy change is able to exploit a policy window that opens as a result of the event [@nohrstedtLogicPolicyChange2010].        

The ACF also notes that policy change can happen as a result of a negotiated agreement between coalitions [@sabatierAdvocacyCoalitionFramework2007]. Negotiated agreements involve deliberation, compromises, and trade-offs between adversarial coalitions, which result in policy changes. Such agreements are more likely in the presence of a "hurting stalemate", or a situation where the status-quo is unacceptable to the coalitions and there are no other policy venues in which to engage [@nohrstedtAdvocacyCoalitionFramework2023]. Finally, policy change can happen as a result of shifts in power between coalitions [@piercePolicyChangeAdvocacy2020]. Power shifts between coalition can happen as a result of events such as an election that favors elected officials of one coalition, newly available resources for a coalition such as a powerful elected official or knowledgeable experts [@nowlinAdvocacyCoalitionsPolitical2022], among others. 

At the heart of our approach to policy learning is information processing, where learning occurs as some information is weighted heavily relative to policy beliefs. However, policy change can happen as a result of attention to information without any changes in belief or preferences [@workmanInformationProcessingPolicy2009]. Policy actors have multiple, and perhaps competing policy preferences, and policy change can happen when one preference becomes more salient than another preference in the absence of learning or preference updating. One example from @jonesChangeMindChange1994 is the consideration of the US Congress in 1991 and again 1992 to fund the construction of the superconducting super collider, a partial accelerator that would have been built in Texas. 79 members of the US House of Representative voted in favor of funding the super collider in 1991, but subsequently voted against funding in 1992. The shift in votes by the 79 members of Congress was likely a result of the issue of the budget deficit gaining more attention and making the preference for a smaller deficit (and perhaps reelection) more salient [@jonesChangeMindChange1994].   
--> 
