# A Model of Policy Learning through Information Processing

## Introduction 

Policy actors and institutions generally have a wide array of information available about potential problems, policy alternatives, and political factors. All of this available information has the potential to contribute to policy learning. Yet actors and institutions are unable to effectively process all available information. Therefore, learning is based on which bits of information receive attention and how they are processed through the belief systems of policy actors and the institutional structures of the policymaking system. 

In this chapter, we develop a model of policy learning through information processing. Building on the Advocacy Coalition Framework’s (ACF) emphasis on policy-oriented learning, we place beliefs and belief systems at the core of the model, since they structure the policy actors' attention to, interpretation, and weighting of incoming information. Additionally, we utilize a Bayesian framework to situate the interaction of beliefs and information processing. A Bayesian approach includes prior beliefs, a likelihood function where information signals are weighed relative to prior beliefs, and posterior beliefs, or beliefs following the processing of information. In brief, learning occurs through selective attention to information signals and their reconciliation with prior beliefs. The model conceptualizes this reconciliation explicitly by treating beliefs as structured priors that organize attention and interpretation, and by treating policy-relevant information as signals that vary in clarity, strength, and credibility. On this view, learning is not synonymous with just any belief shift. Rather, learning is belief updating that is attributable to the interaction between priors and informational cues under identifiable conditions of attention and processing. 

Depending on how information signals compare to prior beliefs, the process can yield several belief-related outcomes, including no learning, belief decay, belief reinforcement, or belief change. We reserve the term learning for belief change that moves in the direction of processed information. The chapter proceeds by first detailing belief systems and their role in policy learning, and then we lay out the learning through information processing model.

## Belief Systems and Learning

The ACF, with its focus on policy-oriented learning as a key driver of policy change, is the policy process theory with the most developed understanding of policy learning. Policy-oriented learning within the ACF is a cognitive process based on policy beliefs, belief systems, and belief change. It is defined as "enduring alterations of thought or behavioral intentions that result from experience, and which are concerned with the attainment or revision of the precepts of the belief systems of individuals or of collectives" [@jenkins-smithDynamicsPolicyOrientedLearning1993, 42]. Hence, learning here involves changes in thought and behavior that result from changes in the belief systems of individuals or collectives. This definition pivots on a cognitive process that produces belief and behavioral change, while also recognizing that learning occurs among individuals and collectives [also see @gerlakBuildingTheoryLearning2011; @heikkilaBuildingConceptualApproach2013].

Beliefs in the ACF manifest in a hierarchical, three-tiered system of belief types, including deep core beliefs, policy core beliefs, and secondary beliefs. Within the belief hierarchy, beliefs move from abstract foundational beliefs – deep core beliefs – to beliefs specific to a policy issue or subsystem – policy core beliefs – to secondary beliefs, which focus on particular means to achieve policy goals. Deep core beliefs inform and constrain policy core beliefs, and deep core and policy core beliefs constrain secondary beliefs. 

Advocacy coalitions are formed around shared policy core beliefs. Policy core beliefs are relevant to a particular policy issue, domain, or subsystem. Additionally, policy core beliefs contain a normative element that "may reflect basic orientation and value priorities for the policy subsystem" such as "whose welfare ... is of greatest concern"; and empirical considerations that involve, "overall assessments of the seriousness of the problem, basic causes of the problem, and preferred solutions for the addressing the problem" [@jenkins-smithAdvocacyCoalitionFramework2018, 140-141]. The components of policy core beliefs reflect the fact that most policy issues are complex and contain multiple attributes. The various attributes of complex policy issues can be considered dimensions in a multi-dimensional issue space [@jochimIssuePoliticsPolarized2013; @jonesPoliticsAttentionHow2005]. 

Policy core beliefs regard complex policy issues that contain multiple dimensions; however, policy actors and institutions are not able to consider all of the possibly relevant dimensions and therefore are likely to only focus on a few dimensions of the issue [@jonesModelChoicePublic2005; @jonesPoliticsArchitectureChoice2001; @jonesBehavioralRationalityFoundation2017]. Apart from being able to only attend to a limited number of dimensions, policy actors also view some dimensions of the issue as more salient or important than others. Therefore, issues can be understood or defined in different ways through various combinations of issue dimensions and their salience. For example, assume the issue of gun violence in the US has two dimensions: ithe prevalence and availability of guns and the mental health of those who commit violent acts using guns. For some, the prevalence of guns is the salient, defining dimension, but for others, the mental health dimension is the important dimension. As a result, the issue of gun violence is defined in two separate ways. Previous work, building on notions of problem definitions, policy images, and frames, notes that the aggregation of the various dimensions weighted by the salience of each dimension constitutes an issue definition [@nowlinModelingIssueDefinitions2016]. Any policy issue, _I_, contains _D_$_\textit{In}$ possible dimensions, and each dimension is weighted _D_$_\textit{In}$($\omega$) with regard to salience. Therefore, issue definitions are the aggregate of the dimensions and their salience, and we argue that such issue definitions constitute the nucleus of policy core beliefs. 

Issue definitions are the sum of the various dimensions of the issue weighted by the salience and form the foundation of policy core beliefs. Policy core beliefs are driven by deep core beliefs. Therefore, deep core beliefs influence the salience weights given to the various issue dimensions. With the gun violence example, the deep core beliefs of conservatism and individualism coupled with normative policy core beliefs that value the rights of gun owners, would likely lead to seeing the mental health of individuals, rather than the availability of guns, as the defining dimension of gun violence. 

It is also important to distinguish between policy beliefs and policy preferences, and to highlight how beliefs influence preferences. As noted by @plumerWhenDoesPolicy2024, policy preferences "refer to the goals of actors within a specific policymaking context" (9). Some argue that policy preferences are policy core beliefs associated with preferred policy approaches and constitute policy core policy preferences [@jenkins-smithAdvocacyCoalitionFramework2018]. While policy beliefs and policy preferences are both cognitive learning products, beliefs exist a priori and inform preferences in the same way beliefs inform attitudes [@fishbeinPredictingChangingBehavior2011; @nowlinEnvironmentalPolicymakingEra2019]. Beliefs can inform the perceived effectiveness of a policy approach, whereas preferences, like attitudes, are stated as "I support" or "I oppose" that policy approach [@moysonCognitionPolicyChange2017; @plumerWhenDoesPolicy2024]. As noted, the hierarchical nature of belief systems means that beliefs range from abstract to particular, with the more abstract beliefs influencing the more particular beliefs. Therefore, secondary beliefs are the beliefs closest to policy preferences. For example, a secondary belief that a carbon tax is an efficient and effective way to address climate change would translate into support for a carbon tax, i.e., a policy preference. 

@fig-defs illustrates our formulation of the relationships between policy beliefs, issue definitions, and policy preferences. 

```{mermaid}
%%| fig-width: 6
%%| fig-height: 2
%%| fig-cap: Policy Beliefs, Issue Definitions, and Preferences
%%| label: fig-defs
%%{init: {'theme': 'base', "themeVariables": { "primaryColor": "#FFFFFF", "primaryBorderColor": "#000000"} } }%%
flowchart LR
    A[Deep Core Beliefs] --> subgraph1
    subgraph subgraph1 [<b>Policy Core Beliefs]
    B[Salience of Issue Dimensions] --> C[Issue Definition]
    end
    subgraph1 --> D[Secondary Beliefs]
    D --> E[Policy Preferences]
```


As shown in @fig-defs, deep core beliefs shape policy core beliefs, which consist of the issue definition, or the aggregated salience of the various issue dimensions. Policy core beliefs inform secondary beliefs, which in turn inform policy preferences. While learning as belief updating could occur for any belief, they become less likely to change as they become increasingly applicable to multiple policy issues. It is rare that deep core beliefs, such as political ideology or cultural worldviews, change, whereas narrowly focused secondary beliefs are the most likely to change. Policy core beliefs are more likely to change than deep core beliefs, but less likely than secondary beliefs. Since preferences follow from beliefs, policy preferences are more likely to change following a change in secondary or policy core beliefs.  

Policy-oriented learning is associated with belief system changes within a subsystem. However, ACF scholarship has also noted that belief reinforcement can be a type of or an outcome of policy-oriented learning [@pattisonFactorsShapingPolicy2018; @nohrstedtAdvocacyCoalitionFramework2023]. Indeed, belief reinforcement seems to be the most common type of policy-oriented learning [@weibleAdvocacyCoalitionsBeliefs2022]. Recent work has proposed that policy learning as change and reinforcement can be explained when policy beliefs are understood as a probability distribution with a central tendency (the belief) and variance (uncertainty about the belief) [@nowlinPolicyBeliefsBelief2024]. With this approach, learning as belief change occurs when there is a shift in the central tendency, and learning as belief reinforcement occurs when there is a reduction in variance. Using this approach, policy-oriented learning outcomes include no change in beliefs (i.e., no learning), belief reinforcement (i.e., a reduction in uncertainty), belief change (i.e., learning, or a significant shift in the central tendency), or belief change and reinforcement (i.e., a shift in beliefs and a reduction of uncertainty) [@nowlinPolicyBeliefsBelief2024]. The likelihood of belief change is a function of the strength of the belief, with firmly held beliefs with low uncertainty less likely to change than less firmly held or less certain beliefs [@nowlinPolicyLearningInformation2021; @jenkins-smithAdvocacyCoalitionFramework2018]. 


<!-- move these context paragraphs to chap 5? -->

<!-- Policy-oriented learning occurs within and across individuals and collectives as part of a collective learning process. More broadly, collective learning can be understood as consisting of two parts, including "(1) a 'collective process,' which may include acquiring new knowledge through diverse actions (e.g., trial and error), assessing information and disseminating new knowledge or opportunities across individuals in a collective, and (2) 'collective products' that emerge from the process, such as new shared ideas, strategies, rules, or policies (@gerlakBuildingTheoryLearning2011, 623). The first part, the process of learning involves acquiring knowledge, whereas the second part, learning products involves the outcomes associated with the process of learning. -->

Belief systems are comprised of deep core beliefs, policy core beliefs that include issue definitions, and secondary beliefs that inform policy preferences. The ubiquity of information surrounding policy actors provides opportunities to learn (i.e., update beliefs). As noted, the interaction between information and heuristics, biases, and beliefs has long been understood as important for policy outcomes [@simonAdministrativeBehaviorStudy1997; @deutschNervesGovernmentModels1963]; yet little work has explicitly focused on these interactions as drivers of learning. Drawing on work developed from Punctuated Equilibrium Theory (PET), we define information as signals about problems and solutions that emanate throughout the policymaking system [@jonesPoliticsAttentionHow2005; @workmanInformationProcessingPolicy2009]. Information processing occurs once policy actors attended to those signals. 

The nature of information and information processing for policymaking is discussed in detail in Chapter 5. Briefly, information for policymaking is imperfect, costly, and asymmetric; however, policy actors face incentives to share information, otherwise they risk allowing other actors to define the policy issue. Therefore, information about policy problems is ubiquitous in the policy process. It comes in the form of information on conditions and problems collected by government agencies (e.g., inflation, unemployment, crime), lobbying by interest groups, media reporting, and public opinion data, among many others. Additionally, focusing events, such as a disaster, terrorist attack, or pandemic provide strong information signals about potential problems [@birklandDisasterAgendaSetting1997; @birklandFocusingEventsMobilization1998; @birklandWorldChangedToday2004; @deleoDisasterRefiningConcept2021]. Information flows need to be processed to determine what, if any, actions are needed. However, given the amount of information present, only some signals are processed, while many are ignored. In the next section, we lay out the learning through information processing model.   

## Learning and Information Processing Model  

Recent work combined policy-oriented learning with insights from the information processing literature to develop a model of policy learning through information processing [@nowlinPolicyLearningInformation2021]. The model focuses on cognitive processes associated with learning and uses a Bayesian framework to illustrate belief change and updating. A Bayesian approach to policy was first applied by scholars of policy diffusion, where learning was seen as an important mechanism for the movement of policy ideas across governments [@braunTakingGaltonProblem2006; @meseguerWhatRoleLearning2004a]. In brief, a Bayesian framework involves a prior belief, information that is attended to and processed through a likelihood function, and a posterior belief that is a function of the prior beliefs and the information. Information signals that receive no or little attention are not processed further. 

In more formal terms and using notation from @druckmanEvidenceMotivatedReasoning2019, the model includes a prior belief that is understood as a probability distribution about the true state of the world expressed as $\pi$($\mu$) ~ _N_($\hat{\mu}_0$, $\hat{\sigma}^{2}_{0}$) where $\pi$($\mu$) is the true state of the world, $\hat{\mu}_0$ is an individual's belief about the state of the world, and $\hat{\sigma}_0$ is their uncertainty about their beliefs. Next, the individual encounters some information, _x_, expressed as _N_($\mu$, $\hat{\sigma}^{2}_{x}$), where $\hat{\sigma}^{2}_{x}$ represents the individual's likelihood function or how she processes and weights the information. Finally, the individual updates her beliefs in light of the information $\pi$($\mu$|x). 

The steps of the learning through information processing model include: 

* **Prior belief**: $\pi$($\mu$) ~ _N_($\hat{\mu}_0$, $\hat{\sigma}^{2}_{0}$) 
* **Processing of information, x (likelihood function)**: _N_($\mu$, $\hat{\sigma}^{2}_{x}$) 
* **Posterior belief**: $\pi$($\mu$|x) 

Under this model, learning only occurs when beliefs or belief certainty change _in the direction of the information_ [@nowlinPolicyLearningInformation2021; @nowlinPolicyBeliefsBelief2024]. In other words, learning occurs only when the updated beliefs are congruent with the processed information. The model focuses on the process of learning and does not consider the validity of beliefs or the information, or how receivers process that information. As noted by @coppockPersuasionParallelHow2023, "people are free to have bonkers prior beliefs and loopy likelihood functions" (123). Additionally, if individuals were perfectly rational and motivated solely for accuracy, then the posterior beliefs would be updated in direct proportion to the information. In other words, a "strong" information signal -- one that is valid, credible, reliable, and reflects the true state of the world -- would lead to shifts in beliefs that reflect the strength of the signal. This type of proportion updating of beliefs has been termed rational learning [@braunTakingGaltonProblem2006; @meseguerPolicyLearningPolicy2005]. However, individuals are not perfectly rational and, therefore, learning may be "bounded" as individuals weight information, as noted by $\hat{\sigma}^{2}_{x}$, based on the strength of their prior beliefs  [@nowlinPolicyLearningInformation2021; @braunTakingGaltonProblem2006; @meseguerPolicyLearningPolicy2005]. As a result, information and information processing may or may not lead to learning. Next, we discuss several possible learning outcomes that result from the learning process described above.  

### Learning Outcomes Related to Beliefs 

The process of learning through information processing leads to several possible outcomes, or products, based on the motivation and biases of the individual or group. As noted, beliefs are probability distributions with a central tendency (the belief), $\hat{\mu}_0$, and uncertainty, $\hat{\sigma}^{2}_{0}$, about the belief. Changes in either belief or certainty are possible outcomes; however, the changes must reflect the information to be considered learning.^[Another possible outcome is a back-lash or boomerang effect, where beliefs move in the opposite direction of the information [@druckmanEvidenceMotivatedReasoning2019; @hartBoomerangEffectsScience2012]. However, in our conceptualization learning from information processing only occurs when the posterior beliefs are congruent with the information, therefore a boomerang effect would not be considered learning even though it is in response to information.]   

Possible learning outcomes associated with beliefs include:

* No learning: No change in beliefs or level of certainty

* Belief decay: A decrease in certainty

* Belief reinforcement: An increase in certainty

* Belief change: A change in the central tendency of the belief distribution

Additionally, belief changes may be coupled with decay and/or reinforcement, as both beliefs and certainty change in response to information. For example, @nowlinPolicyBeliefsBelief2024 finds that following a deliberative mini-public on several environmental issues, participants' beliefs changed in various ways across topics. Participants experienced several possible outcomes, including no learning (no changes in beliefs or certainty), belief changes (a significant shift in the mean), and belief reinforcement (a reduction in uncertainty). Additionally, in some cases, participants experienced both belief change and reinforcement, as beliefs changed in conjunction with a decrease in uncertainty.

As noted, if individuals were fully rational and motivated by accuracy, they would update their beliefs in proportion to the information. However, it is well known that individuals are not comprehensively rational and are often motivated to reach specific conclusions rather than accuracy, which makes belief change in response to information much less likely [@kundaCaseMotivatedReasoning1990; @jonesBehavioralRationalityFoundation2017]. In addition, several possible biases reduce the likelihood that individuals or groups learn from information, including in-group/out-group, confirmation bias, desirability bias, availability bias, negativity bias (loss aversion), anchoring bias, and status quo bias [@heikkilaDiagnosingIndividualBarriers2024].

With the policy learning through information processing model, motivated reasoning and biased information processing are captured by the interaction between prior beliefs and the likelihood function. The likelihood function determines how the information is processed and weighted, yet in most cases, information signals are processed and weighted disproportionately, with some signals ignored and others weighted strongly. In a Bayesian framework, the posterior belief is proportional to the prior belief multiplied by the likelihood function, meaning that a strong prior and/or a strong weighting of information signals will determine the degree to which beliefs change. This process likely underlies many common biases. For example, confirmation bias can be understood as the over-weighting of information that confirms prior beliefs and the under-weighting of information that challenges prior beliefs.

Additionally, the interaction between prior beliefs and the likelihood function varies by belief type. Deep core beliefs would provide strong prior beliefs and act as a filter to weight information. While not impossible, changing deep core beliefs would require an exceptionally strong information signal appropriately weighted. Policy core beliefs are also difficult to change and would require a strong information signal. However, policy core beliefs may erode as different dimensions of an issue shift and become more (less) salient in response to information. Learning at the level of policy core beliefs can occur when an issue is redefined. Finally, secondary beliefs and subsequent policy preferences are the beliefs most likely to change, as the prior beliefs associated with secondary aspects or policy preferences are the least strongly held.      

## Conclusion 

In this chapter, we outlined a model of policy learning based on the interaction of beliefs, including deep core, policy core, and secondary, and information. The model is based in a Bayesian framework with prior beliefs that have a distribution with a central tendency and variance, a likelihood function where information signals are weighted, and posterior beliefs, which are also a distribution and include a central tendency and variance. The central tendency, the variance, or both may shift as a result of information processing. Therefore, the model produces several possible outcomes, including no learning, belief decay, belief reinforcement, and belief change.    

<!-- may need to expand this with examples; ask Bishoy -->
This model of learning is intended to be generalizable enough to capture many of the elements of learning discussed in Chapter 2. For example, the model can be applied to multiple conceptual approaches and theoretical descriptors of learning shown in @tbl-learn-concept. The model focuses on the process and mechanisms of learning as well as learning outcomes. While it is grounded in micro-foundations, its insights can be scaled to the meso and macro level (see @tbl-learn-levels), as we assume a similar learning process for individuals and collectives. Finally, the model can account for various types, modes, mechanisms, forms, and degrees of learning shown in @tbl-learn-descript. In the next chapter, we examine the model empirically using US public opinion data about nuclear energy before and after the Fukushima nuclear accident. 





