# Introduction

## Policy Learning: A Background

Why do policy actors do what they do? Why and how does a policy change or remain immutable? Those are some of the most quintessential puzzles in public policy research and practice. Several theoretical approaches and frameworks have endeavored to solve these puzzles. For example, by focusing on changes in beliefs and coalitions [@sabatierPolicyChangeLearning1993], institutional arrangements [@ostromGoverningCommonsEvolution1990], mechanisms of policy adjustment [@lindblomScienceMuddling1959], policy dynamics and patterns of policy change [@baumgartnerAgendasInstabilityAmerican1993], or the role of policy entrepreneurs in coupling problems, solutions, and political conditions, [@kingdonAgendasAlternativesPublic1984], among others.

While these different theoretical approaches provided substantial insights into the particularities of policy change, policy learning as an approach to understand policy change is perhaps one of the most fundamental and promising approaches to explaining policy change and stability. As discussed in detail in Chapter 1, a recent review of policy learning scholarship found over 30 definitions for policy learning [@zakiSystematicReviewPolicy2022]. However, many of those definitions were variants of policy-oriented learning from the Advocacy Coalition Framework (ACF). Policy-oriented learning is defined as "enduring alterations of thought or behavioral intentions that result from experience and which are concerned with the attainment or revision of the precepts of the belief systems of individuals or collectives" [@jenkins-smithDynamicsPolicyOrientedLearning1993, 42].

Among the various theories of the policy process, the ACF, through its focus on the connections between belief systems, belief change, and policy-oriented learning has one of the most substantive conceptualizations of the policy learning and policy change nexus [@bandelowLearningNecessaryNot2019; @jenkins-smithDynamicsPolicyOrientedLearning1993; @nohrstedtAdvocacyCoalitionFramework2023; @pattisonFactorsShapingPolicy2018]. However, the fundamental nature of policy learning has helped it proliferate across different theoretical approaches to the policy process. Accordingly, several of the theories and frameworks of the policy process discuss policy learning, at least implicitly. For example, within the Multiple Streams Approach, learning has been observed to occur in epistemic communities in the policy stream through changes in indicators in the problem stream and experimenting with various political strategies in the politics stream [@herwegMultipleStreamsFramework2023]. Furthermore, within the same framework, learning has also been linked to the key process by which policy entrepreneurs "couple" the different streams [@blumMultipleStreamsFrameworkKnowledge2018]. Learning also crystallizes across different theories of the policy process, from policy diffusion and transfer [@voldenFormalModelLearning2008] to the stages approaches to policymaking, from policy design to implementation [@zakiPolicyLearningGovernance2024; @biegelbauerHowDifferentForms2016]. Additionally, policy learning has integrated into, technical and social understandings of policy problems [@bennettLessonsLearningReconciling1992], policy advocacy [@zakiUnderstandingPoliticalLearning2024], levels of policy change [@bennettLessonsLearningReconciling1992; @hallPolicyParadigmsSocial1993; @hecloModernSocialPolitics1974; @moysonPolicyLearningPolicy2017], and policy entrepreneurship [@blumMultipleStreamsFrameworkKnowledge2018]. Overall, policy learning has gained prominence across the board throughout policy analysis and policy process scholarship [@bennettLessonsLearningReconciling1992; @bennettLessonsLearningReconciling1992; @dunlopPolicyLearningComparative2022].

Apart from contributing to policy process theories, policy learning may constitute its own analytical framework [@dunlopDoesPolicyLearning2018]. Going further, policy learning may not only be a theoretical lens on the policy process, but it may also function as an ontology of policymaking. In other words, its nature is a fundamental process that shapes individual and collective behavior within the policy process [@kamkhajiPolicyLearningEuro2022]. This stems from the background understanding of policy learning as a fundamental problem-solving process in which policy actors seek and process information and knowledge about policy problems, aiming to develop viable solutions while considering how this interacts with existing cognitive and institutional structures in which problem-solving occurs. In this way, policy learning is *embedded* into the fabric of policymaking [@zakiSystematicReviewPolicy2022]. This process can lead to cognitive outcomes where policy actors update their knowledge and beliefs about policy problems or behavioral products, such as different degrees of policy change [@dunlopSystematisingPolicyLearning2013]. Accordingly, an ontological view of policy learning ascribes that we can better explain policy behaviors and policy outcomes if we understand the key aspects of learning (i.e., who learns, what they learn, from whom, how, and why). In other words, we can better explain why policy actors behave in a certain way and the consequences of their actions as a function of their learning processes [@zakiPracticingPolicyLearning2024].

The theoretical status of policy learning and its role in shaping policymaking processes and outcomes are rooted in empirical accounts. For example, research shows that if policy actors learn optimally (i.e., from the right sources, at the right time, employing adequate modes of learning), they have higher chances of developing practical solutions to policy problems, delivering substantive reforms, or improving policy performance [@starkPolicyLearningPublic2019; @waiyipsoSuWeiYeLearningKeyCitizencentred2012]. However, learning is not optimally approached when expertise, knowledge, and learning modes are misidentified or misused. In that case, policy learning can become misdirected, leading to policy failures or fiascos [@dunlopCantGetNo2020] or even value destruction [@zakiHelloDarknessMy2024]. As a result, we increasingly see policy actors attempting to deliberately design and develop robust and effective policy learning processes [@zakiPolicyLearningGovernance2024]. This manifests across a wide range of policy domains, from public health to agriculture and food security to crisis governance and beyond [@albrightPolicyChangeLearning2011a; @beachPresentRoleAnalogical2021; @busettiPolicyLearningCrises2023; @crowPolicyLearningChange2023].

At the heart of our approach to policy learning is information and its processing. Information constitutes the raw material with which ideas, knowledge, beliefs, and social construction of policy problems are built [@nowlinPolicyLearningInformation2021; @zakiSystematicReviewPolicy2022]. Within learning, individuals and collectives exchange informational cues about policy problems and then reconcile and process them within existing norms, heuristics, beliefs, and preferences. Accordingly, they develop updated understandings of these problems and their potential solutions, guiding policymaking [@beachPresentRoleAnalogical2021; @wagnerCanPolicyForums2020]. How these informational cues are exchanged, selected, and processed significantly impacts what is learned and the products of learning [@heikkilaBuildingConceptualApproach2013; @moysonCognitionPolicyChange2017; @nowlinPolicyLearningInformation2021]. With information and information processing at the core, we define policy learning as an updating of beliefs following the processing of information. Furthermore, the updated beliefs must be congruent with the information to be considered learning.

However, despite being understood as a key aspect of policy learning, especially over recent years, the role of information processing as a micro foundational dimension of policy learning is often under-theorized [but see @nowlinPolicyLearningInformation2021]. Policy process work on information and information processing developed by scholars of Punctuated Equilibrium Theory (PET) [see @jonesThereHerePunctuated2012] and largely independent from policy process work on policy learning. This is even though several decades ago, trailblazers in the field, such as @simonAdministrativeBehaviorStudy1997 and @deutschNervesGovernmentModels1963, among others, pointed to the need for recognizing the cybernetic nature of policymaking and policy learning where the interaction between information and heuristics, biases, and reasoning paradigms substantively shapes policy outcomes. The relative scarcity of theoretical focus on the connections between information processing and policy learning somewhat limits the field’s ability to explain the underlying causal mechanisms by which policy actors learn how they do and consequently explain their learning outcomes. This is particularly problematic given the importance of integrating multilevel views of policy learning (micro, meso, and macro) in describing how learning aggregates towards specific outcomes [see @dunlopPolicyLearningEurozone2016; @heikkilaBuildingConceptualApproach2013; @zakiSystematicReviewPolicy2022].

In this Element, we build on work that situates learning at the core of policymaking, where learning is embedded in a policy context with policy actors, governance structures, and information [@zakiSystematicReviewPolicy2022]. Specifically, we focus on the role of information within the policy-embedded learning framework by synthesizing research on learning and information processing to offer insights on how information processing dynamics (i.e., attention to some information signals while ignoring or downplaying others) influences what is or isn't learned and how this contributes to changes in policy learning outcomes. Doing so advances the theoretical debate on learning by further enshrining the micro foundational and fundamental information processing dimension within existing approaches to policy learning and plotting how they influence policy learning processes. This helps provide a more robust baseline for aggregating how learning takes place across multiple levels and thus advances our ability to explain learning outcomes and how learning contributes to policy change [@dunlopLearningBathTubMicro2017; @moysonPolicyLearningPolicy2017].

Looking ahead, in Chapter 1, we provide a thorough overview of the foundations of policy learning as a field of study and its development. Then, we showcase how these foundations developed into the contemporary sprawling landscape of policy learning research and its main analytical, theoretical, and conceptual streams (i.e., types, forms, mechanisms, modes of learning, etc.). From there on, we discuss the different ontological approaches to policy learning while dedicating special attention to the role of information processing therein. In Chapter 2, we examine policy-embedded learning as a framework and conceptual background for thinking about the role of information and information processing in learning. Next, in Chapter 3, we discuss the role of belief systems and information processing in policy learning, from which we build a model of policy learning through information processing. Then, in Chapter 4, we empirically apply the model to the case of the United States public opinion about nuclear energy following the Fukushima nuclear disaster. While much of our discussion centers on learning among elite policy actors, we rely on public opinion data because ... often used by policy process scholars to examine belief systems ... belief systems of the public and elites have a similar structure ... those with a college (or graduate) degree

Finally, in Chapter 5, we offer a set of brief concluding remarks that connect our model and framework to the conceptual, analytical, and theoretical approaches to learning discussed within this element. This also includes a discussion of the limitations of this approach, most notably how policy change happens outside of policy learning through information processing.