---
title: "Chapter 2: Information Processing and Policy-Embedded Learning"
bibliography: /Users/nowlinmc/Dropbox/refs.bib
csl: /Users/nowlinmc/Dropbox/Projects/Manuscript-Files/csl/american-political-science-association.csl
fig-cap-location: top
fontfamily: ebgaramond
link-bibliography: false
format: docx 
---

# Introduction 

Information is not a scarce resource for policymaking. Policy actors and policymaking institutions are bombarded with information from a variety of sources. As a result, attention to information, specifically the inability of actors or institutions to attend to all information, becomes the limiting factor for how information is translated into policy learning and, ultimately, to policy change. Individuals and institutions have limited capacity to process information, and, as a result, information is processed in a disproportionate manner. Disproportionate information processing limits the policy learning that can occur from information that is potentially relevant. 

Attention to some information rather than other information is driven by several factors, including the beliefs, biases, and motivations of policy actors. Actors who are motivated for accuracy would likely process information differently than those motivated to reach or maintain a specific conclusion [@kundaCaseMotivatedReasoning1990; @druckmanEvidenceMotivatedReasoning2019]. Along similar lines, prior beliefs can shape how information is processed by leading policy actors to weight information based on accordance with beliefs [@nowlinPolicyLearningInformation2021]. In some instances policy actors may seek to limit attention to some problem indicators to avoid blame or for ideological reasons to limit government actions. For example, at a campaign rally in June 2020, President Trump, discussing COVID testing, noted, "When you do testing to that extent, you’re going to find more people, you’re going to find more cases ... So I said to my people, ‘Slow the testing down, please.’ They test and they test” [@frekingTrumpSuggestsUS2020]. In each of these instances, the potential for policy learning is shaped by how information is processed and what information does, or does not, receive attention.  

In this chapter, we examine information and policy learning in the broader context of policymaking processes. Specifically, we draw on policy process theories, including the Advocacy Coalition Framework (ACF) and Punctuated Equilibrium Theory (PET) to develop a model of policy learning and information initially introduced by @nowlinPolicyLearningInformation2021. Next, we discuss the information processing and learning model in the context of the policy-embedded learning framework [@zakiSystematicReviewPolicy2022] to illustrate how the model accounts for policy learning among policy actors at the micro and macro level. Additionally, by joining the learning and information processing model and the policy-embedded learning framework, we can illustrate how learning embedded in institutions and issue contexts can generate several potential learning outcomes.  

# Learning and the Policy Process 

Several of the theories and frameworks of the policy process discuss policy learning, at least implicitly. For example, within the Multiple Streams Approach, learning can occur in epistemic communities in the policy stream, through changes in indicators in the problem stream, and experimenting with various political strategies in the politics stream [@herwegMultipleStreamsFramework2023]. Additionally, learning may be part of the policy diffusion or transfer process as one government learns from another [@voldenFormalModelLearning2008]. 

Among the various policy process theories and frameworks, the Advocacy Coalition Framework (ACF) has the most developed conceptualization of policy learning. Within the ACF, policy-oriented learning is a cognitive process based in policy beliefs and belief change. Specifically, policy-oriented learning is "enduring alterations of thought or behavioral intentions that result from experience, and which are concerned with the attainment or revision of the precepts of the belief systems of individuals or of collectives" [@jenkins-smithDynamicsPolicyOrientedLearning1993, 42]. Learning involves changes in _thought_ and _behavior_ that result from changes in the _belief systems_ of _individuals_ or _collectives_. This definition includes a cognitive process that produces belief and behavior change and recognizes that learning occurs among individuals and collectives [also see @gerlakBuildingTheoryLearning2011; @heikkilaBuildingConceptualApproach2013].

Early work using the ACF noted that changes in the overall "distributions of beliefs" within a subsystem might result from one or more processes, including

> 1) individual learning and attitude change, 2) the diffusion of new beliefs and attitudes among individuals, 3) turnover in individuals within any collectivity, 4) group dynamics, such as the polarization of homogenous groups or groups in conflict, and 5) rules for aggregating preferences and for promoting (or impeding) communication among individuals [@jenkins-smithDynamicsPolicyOrientedLearning1993, 42].

The first two processes involve the role of policy-oriented learning in belief system changes within a subsystem, yet the majority of work has focused on the first process: individual learning and attitude (i.e., belief) change. However, ACF scholarship has also noted that belief reinforcement can be a type of or an outcome of policy-oriented learning [@pattisonFactorsShapingPolicy2018]. In fact, belief reinforcement is likely the most common kind of policy learning [@weibleAdvocacyCoalitionsBeliefs2022]. Recent work has proposed that policy learning as change and reinforcement can be explained when policy beliefs are understood as a probability distribution with a central tendency (the belief) and variance (uncertainty about the belief) [@nowlinPolicyBeliefsBelief2024]. With this approach, learning as belief change occurs when there is a shift in the central tendency, and learning as belief reinforcement occurs when there is a reduction in variance. More broadly, using this approach, policy-oriented learning outcomes include no change in beliefs (i.e., no learning), belief reinforcement (i.e., a reduction in uncertainty), belief change (i.e., learning, or a significant shift in the central tendency), or belief change and reinforcement (i.e., a shift in beliefs and a reduction of uncertainty) [@nowlinPolicyBeliefsBelief2024]. The likelihood of belief change is a function of the strength of the belief, with strongly held beliefs with low uncertainty less likely to change than less strongly held or less certain beliefs [@nowlinPolicyLearningInformation2021; @jenkins-smithAdvocacyCoalitionFramework2018].    

<!-- more about context of learning forums; deliberation -->

As noted, learning occurs within and across individuals and collectives, with policy-oriented learning most likely to happen as part of a collective learning process. More broadly, collective learning can be understood as: 

> 1) a "collective process", which may include acquiring information through diverse actions (e.g. trial and error), assessing or translating information, and disseminating knowledge or opportunities across individuals in a collective, and 2) "collective products" that emerge from the process, such as new shared ideas, strategies, rules, or policies [@gerlakBuildingTheoryLearning2011, 623]. 

With this definition, learning is a _process_ that results in one or more _products_. The process of learning involves the, "(i) acquisition; (ii) translation; and (iii) dissemination of knowledge, information, and experience" [@heikkilaBuildingConceptualApproach2013, 487]. Learning products are cognitive, such as changed or reinforced beliefs, and behavioral, including new strategies and policy change [@heikkilaBuildingConceptualApproach2013]. 

Additionally, learning occurs both within coalitions and between coalitions. Learning within coalitions is relatively straightforward given the nature of the shared beliefs; however, learning between coalitions is, in part, a function of the collective context in which information is processed and the issues are discussed. According to ACF scholarship, learning across coalitions is more likely when a) there is an intermediate level of conflict because in such contexts, coalitions have the resources to engage and the core beliefs of both coalitions are not at stake; b) issues that are analytically tractable and high-quality data is available; and c) a forum that encourages participation of representatives of the various coalitions and professional norms of engagement [@jenkins-smithDynamicsPolicyOrientedLearning1993]. 

Another important collective context for learning is the nature of the policy subsystem in which policy actors engage. Subsystems are the key unit of analysis within the ACF, and they can vary on several key dimensions. As noted by @weibleExpertBasedInformationPolicy2008, subsystems can be unitary, collaborative, or adversarial. Unity subsystems involve one dominant coalition and a single understanding of the policy issue. Policy-oriented learning in unitary subsystems happens within the dominant coalition and is likely belief reinforcement [@weibleExpertBasedInformationPolicy2008]. Additionally, in unitary subsystems, policy-oriented learning as belief change is likely impeded by the status-quo bias of the dominant coalition and the negative feedback that is exerted regarding new information [@jonesPoliticsAttentionHow2005]. Collaborative subsystems involve cooperative coalitions with a shared understanding of the policy issue and learning as both belief change and belief reinforcement may occur within and across coalitions. Finally, adversarial subsystems include two or more coalitions competing for policy influence with a debated understanding of the policy issue. Given that beliefs are contested in adversarial subsystems, belief reinforcement within coalitions is the most likely policy-oriented learning in an adversarial subsystem.  

Finally, the information available about the issue and how that information is processed is a key context. In the next section, we focus on the role of information and information processing in the process of learning. Specifically, we discuss the policy process literature about information processing and then build on the model developed by @nowlinPolicyLearningInformation2021.  

# Information Processing 

The work on information processing in public policy has been developed by scholars using the Punctuated Equilibrium Theory (PET) of the policy process [@baumgartnerPoliticsInformationProblem2015; @baumgartnerPunctuatedEquilibriumTheory2023; @jonesPoliticsAttentionHow2005; @jonesThereHerePunctuated2012; @baumgartnerAgendasInstabilityAmerican1993]. PET explains policy processes that involve periods of stability and incremental change coupled with periods of large, rapid, and punctuated change. In brief, PET posits that stability and incremental change are a product of issues being contained within a subsystem, and punctuations occur as issues move from a subsystem to the macro-institutions of policymaking through positive feedback, changing policy images, shifting policy venues, and/or new policy actors becoming engaged. PET has expanded to a theory of information processing and attention in political systems. 

Information and the prioritization and processing of information are key to the policy process [@workmanInformationProcessingPolicy2009]. In the information processing approach, information is understood as “signals of change” that emanate from the environment, and information processing is the “collecting, assembling, interpreting, and prioritizing” of those signals [@jonesPoliticsAttentionHow2005, 7].  Information signals that flow into the policymaking system vary but can be categorized as belonging to one of the streams identified by the Multiple Streams Approach, including information about the problem, possible policy approaches, and the politics surrounding the issue [@nowlinEnvironmentalPolicymakingEra2019]. Information processing involves processing information signals; however, given that the supply of information possibly relevant for policymaking is large, neither individuals nor institutions can adequately process the vast number of information signals they receive. This dynamic leads to disproportionate information processing, where some signals are overemphasized and others are ignored. Additionally, policy actors may purposefully attend to some information and not other information. Eventually, information signals that have been ignored may accumulate and lead to punctuated policy change.

As noted, the process of learning involves the acquisition, translation, and dissemination of information [@heikkilaBuildingConceptualApproach2013], and along similar lines, @jonesPoliticsAttentionHow2005 argue that information processing involves four stages, including a recognition stage, a characterization stage, an alternative stage, and a choice stage. The learning processes occur in similar ways at both the individual and the collective level. 

The acquisition stage involves the acquiring of information by individuals, which may happen through experience, observation, search, and/or deliberation [@heikkilaBuildingConceptualApproach2013]. Similarly, the recognition stage involves the allocation of attention to particular policy problems and information signals. The recognition stage translates to agenda-setting at the collective level. For learning through information processing to occur, information must first be acquired and attended to. 

Next, information is translated or interpreted through concerted effort and analysis or through unintentional processes that are influenced by framing or the heuristics of the individual [@heikkilaBuildingConceptualApproach2013; @heikkilaDiagnosingIndividualBarriers2023]. For @jonesPoliticsAttentionHow2005, the next stage is the characterization stage, where the various attributes or dimensions of the problem are considered. Most policy issues are complex and can be understood and defined in a variety of different ways, and the characterization stage involves policy actors assembling and weighting the various dimensions of the issue to develop the issue definition [@nowlinModelingIssueDefinitions2016]. 

Following the characterization stage is the alternative stage, where policy alternatives are developed. As with the characterization stage, the alternative stage is multidimensional, and several possible policy alternatives are available. The understanding and definition of the problem constitute a multidimensional problem space, and the policy alternatives are a multidimensional solution space [@baumgartnerPoliticsInformationProblem2015]. Often, the dimensions of the issues weighted heavily in the construction of the problem space imply particular approaches in the solution space. Different types of information are needed to construct the problem space versus the solution space. Additionally, these spaces can evolve independently, much like the problem and policy streams [@kingdonAgendasAlternativesPublic1984; @herwegMultipleStreamsFramework2023]. When considering which problems to prioritize, it is best to get information from a diverse array of sources to develop a better understanding of the problem. This type of information is termed _entropic_ [@baumgartnerPoliticsInformationProblem2015]. Institutional structures that are decentralized can facilitate this type of learning [@eppStructurePolicyChange2018; @heikkilaBuildingConceptualApproach2013]. However, when considering how to address problems, it is best to rely on expert information. 

For @heikkilaBuildingConceptualApproach2013, the final part of the learning process is dissemination, where individuals share knowledge within a collective. Shared collective routines, communication practices, and deliberation may help facilitate the dissemination of information. Additionally, @heikkilaBuildingConceptualApproach2013 note that dissemination may inform the agenda-setting process and can therefore play into the recognition stage. The final stage for @jonesPoliticsAttentionHow2005 is the choice stage, where a policy alternative from the solution space is selected for support by an individual or selected as a policy by a policymaking institution. However, we consider choice to be a product of the learning process. In the next section, we discuss a model of information processing and policy learning.       

# Model of Policy Learning and Information Processing 

Recent work combined policy-oriented learning with insights from the literature on information processing to develop a model of policy learning through information processing [@nowlinPolicyLearningInformation2021]. The model is focused on cognitive processes associated with learning and uses a Bayesian framework to illustrate belief change or updating. Additionally, the model can be applied to learning by both individuals and collectives. In brief, a Bayesian framework involves a prior belief, information that is processed through a likelihood function, and a posterior belief that is a function of the prior beliefs and the information. In more formal terms and using notation from @druckmanEvidenceMotivatedReasoning2019, a prior belief is understood as a probability distribution about the true state of the world expressed as $\pi$($\mu$) ~ _N_($\hat{\mu}_0$, $\hat{\sigma}^{2}_{0}$) where $\pi$($\mu$) is the true state of the world, $\hat{\mu}_0$ is an individual's belief about the state of the world, and $\hat{\sigma}_0$ is their uncertainty about their beliefs. Next, the individual encounters some information, _x_, about the true state of the world expressed as _N_($\mu$, $\hat{\sigma}^{2}_{x}$), where $\hat{\sigma}^{2}_{x}$ represents the individual's likelihood function or how she processes and weights the information. Finally, the individual updates her beliefs in light of the information $\pi$($\mu$|x). 

The steps of the learning through information processing model include: 

* **Prior belief**: $\pi$($\mu$) ~ _N_($\hat{\mu}_0$, $\hat{\sigma}^{2}_{0}$) 
* **Processing of information, x (likelihood function)**: _N_($\mu$, $\hat{\sigma}^{2}_{x}$) 
* **Posterior belief**: $\pi$($\mu$|x) 

Under this model, learning only occurs when beliefs or belief certainty changes in the direction of the information [@nowlinPolicyLearningInformation2021; @nowlinPolicyBeliefsBelief2024]. The model is about the process of learning and does not consider the validity of the beliefs or the information. As noted by @coppockPersuasionParallelHow2023, "people are free to have bonkers prior beliefs and loopy likelihood functions" (123). Additionally, if individuals were perfectly rational and motivated solely for accuracy, then the posterior beliefs would be updated in direct proportion to the information. In other words, a "strong" information signal -- one that is valid, credible, reliable, and reflects the true state of the world -- would lead to shifts in beliefs that reflect the strength of the signal. However, individuals are not perfectly rational and, therefore, will weight the information, as noted by $\hat{\sigma}^{2}_{x}$, often based on the strength of their prior beliefs [@nowlinPolicyLearningInformation2021]. As a result, information may or may not lead to learning. Next, we discuss several possible learning outcomes that result from the learning process described above.  

## Learning Outcomes Related to Beliefs 

The process of learning leads to one or more possible outcomes, or products based on the motivation and biases of the individual or group. As noted, beliefs are probably distributions with a central tendency (the belief), $\hat{\mu}_0$, and uncertainty, $\hat{\sigma}^{2}_{0}$, about the belief. Changes in either the belief or certainty are a possible outcome; however, the changes must reflect the information to be considered learning.^[Another possible outcome is a back-lash or boomerang effect, where beliefs move in the opposite direction of the information [@druckmanEvidenceMotivatedReasoning2019; @hartBoomerangEffectsScience2012]. However, in our conceptualization learning from information processing only occurs when the posterior beliefs are congruent with the information, therefore a boomerang effect would not be considered learning even though it is in response to information.]   

Possible learning outcomes associated with beliefs include: 

* No learning: No change in beliefs or certainty 
* Belief decay: A decrease in certainty 
* Belief reinforcement: An increase in certainty 
* Belief change: A change in the central tendency of the belief distribution 

In addition, changes in beliefs may be coupled with decay and/or reinforcement as both the beliefs and the certainty change in response to information. For example, @nowlinPolicyBeliefsBelief2024 found that following a deliberative mini-public about several environmental issues, the beliefs of participants changed in various ways on different issues. On some issues, participants experienced no learning (no changes in beliefs or certainty) following the deliberation, while on other issues participants, saw belief changes (a significant shift in the mean) and belief reinforcement (a reduction in uncertainty). However, on other issues, participants saw belief change and reinforcement, where beliefs changed in conjunction with a decrease in uncertainty. 

As noted, if individuals were comprehensively rational and motivated for accuracy, then they would update their beliefs in a way that is proportionate to the information. However, it is well known that individuals are not comprehensively rational and are often motivated to reach specific conclusions rather than accuracy, which makes belief change in response to information much less likely [@kundaCaseMotivatedReasoning1990; @jonesBehavioralRationalityFoundation2017]. In addition, there are several possible biases that reduce the likelihood that individuals or groups learn in light of information, including in-group/out-group, confirmation bias, desirability bias, availability bias, negativity bias (loss aversion), anchoring bias, and status quo bias [@heikkilaDiagnosingIndividualBarriers2023]. 

With the policy learning through information processing model, motivated reasoning and biased information processing are captured by the interaction between prior beliefs and the likelihood function. The likelihood function is how the information is processed and weighted, and information signals are processed and weighted in a disproportionate manner, with some signals ignored and others weighted strongly. In a Bayesian framework, the posterior belief is proportional to the prior belief multiplied by the likelihood function, which means that a strong prior and/or a strong weighting of information signals will determine the degree to which beliefs change or not. This process likely underlies many common biases. For example, confirmation bias can be understood as the over-weighting of information that confirms prior beliefs and the under-weighting of information that challenges prior beliefs. 

<!-- may need a discussion of when learning in the more of less likely -->

Policy learning through information processing occurs among policy actors operating within and across institutions. In the next section, we draw on the notion of policy-embedded learning and combine it with the policy learning through information processing model to develop a framework that illustrates possible mechanisms through which information translates to learning and policy change.  

# Policy Embedded Learning 

The notion of policy-embedded learning developed through a systematic review of the policy learning literature [@zakiSystematicReviewPolicy2022]. By closely examining the literature @zakiSystematicReviewPolicy2022 were able to draw several important concepts associated with learning, including information and knowledge; systems and structures; and policy actors. These concepts interact within a particular policy context. As noted by @zakiSystematicReviewPolicy2022, "we conceptualize policy learning as the circulation and consumption of policy issue-related information and knowledge among actors in a policy system and structure, within a policy context" (22). 

**Bishoy** 


@fig-model shows a framework for information processing and policy-embedded learning. 

```{mermaid}
%%| fig-cap: Information Processing and Policy-Embedded Learning
%%| label: fig-model
%%{init: {'theme':'neutral'}}%%
flowchart LR
    subgraph subgraph1 [<b>Information Processed by... </b>]
	direction TB
    B[Systems/ <br> Structures] <--> C[Policy <br> Actors]
    end
    A[Information] --> subgraph1
    subgraph1 --> D[<b> Learning </b> <br> Policy Issue]
    D --> subgraph1
    subgraph subgraph2 [<b>Results in...</b>]
    direction TB
    E[<em> Belief </em> Change] --> 
    F[<em> Preference </em> Change] -->
    G[<em> Behavior </em> Change] -->
    H[<em> <b> Policy Change </b> </em>]
    end
    D --> subgraph2
```


Information is ubiquitous in the policy process. It comes in the form of information about conditions and problems collected by government agencies (e.g., inflation, unemployment, crime); lobbying by interest groups; reporting by the media; public opinion data, among many others. Information flows need to be processed to determine what, if any, actions need to be taken. As discussed above, given the amount of information that is present, only some information signals are processed and many others are ignored. 

The processing of information involves policymaking institutions and the systems and structures they create, as well as the policy actors involved in those institutions. Institutions are structured to allow for the parallel processing of information; however, institutions can only take a small number of actions at a time. For example, legislative institutions can process information about multiple issues through a committee structure, yet they can only vote on one piece of legislation at a time. The systems and structures of institutional arraignments create friction that slows the path of information processing to learning to action, which leads to disproportionate information processing. The disproportionate processing of information leads to under and over-reactions to information as well as a punctuated process of learning and policy change where problems are left unaddressed until a major policy change is needed.     

As discussed, policy learning through information processing occurs as beliefs are updated in response to information. In the context of policy-embedded learning, learning through information processing happens within a policy context and about a policy issue. Specifically, learning about policy issues involves changes in how the issues are defined or understood. Policy issues contain multiple dimensions, and issue definitions involve how those dimensions are weighted, bundled, and placed together [@nowlinModelingIssueDefinitions2016]. Learning with regard to policy issues involves changes in the dimensions of the issue as a result of information and information processing. Similar to policy subsystems, issue definitions can reach static equilibrium points and learning shifts that equilibrium as new dimensions are added or current dimensions are reconsidered. 

Several results of learning are possible. As shown in @fig-model, these outcomes include belief change, policy preference change, behavior change, and policy change; however, at its core, policy learning involves changes in beliefs, and other learning outcomes are downstream of belief changes. Once belief change occurs, policy actors may engage in different behaviors or develop different strategies to obtain their goals. Policy change may then occur as a result of different behaviors. 

The conditions under which policy learning leads to policy change has long been a central question, yet establishing how learning causes policy change has been elusive [@bennettLessonsLearningReconciling1992; @zakiPolicyLearningGovernance2024]. Previous research has gained analytical traction on this issue by separating the process of learning from the products of learning, thus allowing insights into how learning processes connect to learning products (or outcomes) such as policy change [@heikkilaBuildingConceptualApproach2013]. More recently, @plumerWhenDoesPolicy2024 developed a "Learning Product Framework" that examines "three central features of learning products", including "(1) whether the observed learning product reflects a change in policy beliefs , (2) whether it signifies a change in policy preferences, and (3) whether it results in a change in policy outputs" (7). Building on the Learning Product Framework, we also include behavior change as a central feature of learning products that makes policy change more likely.

The learning products of belief change, preference change, and behavior change creates distinct pathways to policy change. The product of belief change, as discussed in Chapter 2, involves information processing and change in the direction of information. Preference change involve changes in the goals policy actors are hoping to obtain [@plumerWhenDoesPolicy2024;@moysonCognitionPolicyChange2017]. The distinction between policy beliefs and preferences will be discussed in the next section. Finally, policy actors may change or adapt new behaviors as policy beliefs and preferences change. Additionally, behavior change may involve, "new or enhanced informal routines and strategies, [...] new or expanded programs and plans that structure group behavior, or highly formalized rules or sets of institutional arrangements and policies" [@heikkilaBuildingConceptualApproach2013, 491-492]. 

The causal pathways from policy learning to policy change include three possible outcomes, including no policy change, non-congruent policy change, and congruent policy change [@plumerWhenDoesPolicy2024]. No policy change results when only beliefs change or only beliefs and preference change, without a subsequent change in policy. Non-congruent policy change happens when policy change occurs but is not aligned with the changed beliefs and preferences. The final pathway noted by @plumerWhenDoesPolicy2024 is congruent policy change, where policy change matches the changed policy beliefs and preferences. To this approach, we add congruent and non-congruent behavior change that precedes policy changes. Non-congruent behavior change involve changes in behaviors that do not align with updated beliefs and preferences, whereas congruent behavior change does align.     


| **Belief Change** | **Preference Change** | **Behavior Change** | **Policy Change** | 
| --- | ---: | ---: | ------: | 
| X | | | | 
| X | X | | | 
| X | X | X (non-congruent) | | 
| X | X | X (non-congruent) | X (non-congruent) | 
| X | X | X (congruent) | | 
| X | X | X (congruent) | X (congruent) | 

: Pathways of Policy Learning and Policy Change {#tbl-paths}

@tbl-paths, adapted from @plumerWhenDoesPolicy2024, shows the various pathways through which policy change as a result of policy learning through information processing may happen. As each learning product happens, the liklihood of policy change through policy learning increases; however, non-congruent changes in behavior and policy are also likely as changes may not align with updated beliefs and preferences. 



{{< pagebreak >}} 

## References 


